### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table interactions has no column named platform

### ISSUE THREAD

**Issue by caiqinghua** [Shaunwei/RealChar#100]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table interactions has no column named platform
[SQL: INSERT INTO interactions (client_id, client_message, server_message, timestamp, platform, action_type) VALUES (?, ?, ?, ?, ?, ?)]

**Comment by johndpope** [comment]
close

**Comment by pycui** [comment]
Closing, issues like this are result of not running `alembic upgrade head`. I will make it clear in the README.
