### ISSUE TITLE
Review added at repo-reviews.github.io

### ISSUE THREAD

**Issue by richardanderson001** [Shaunwei/RealChar#102]
### Thank you for building **RealChar**!

@richardanderson001 created a review titled:

*Realtime Character AI platform,*

on [repo-reviews.github.io](https://repo-reviews.github.io) to share their experience using **RealChar**.

[link to review](https://repo-reviews.github.io//reviews/2023-07-18_richardanderson001_Shaunwei_RealChar)

If you would like to help your super-users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

We hope that sharing these experiences helps your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by pycui** [comment]
Nice! Thanks for the review. Bookmarked this page too.

**Comment by richardanderson001** [comment]
Thanks!  Just fixed the urls in the review as well- looking forward to seeing what's next!
