### ISSUE TITLE
how to solve[lib incompatible error] on Ubuntu Server 20.04 LTS 64[thanks!!!]

### ISSUE THREAD

**Issue by jackdong888** [Shaunwei/RealChar#104]
ERROR: anthropic 0.3.4 has requirement pydantic<2.0.0,>=1.9.0, but you'll have pydantic 2.0.3 which is incompatible.
ERROR: clickhouse-connect 0.6.6 has requirement urllib3>=1.26, but you'll have urllib3 1.25.8 which is incompatible.
ERROR: chromadb 0.3.29 has requirement fastapi==0.85.1, but you'll have fastapi 0.100.0 which is incompatible.
ERROR: chromadb 0.3.29 has requirement pydantic<2.0,>=1.9, but you'll have pydantic 2.0.3 which is incompatible.
ERROR: elevenlabs 0.2.19 has requirement pydantic<2.0,>=1.10, but you'll have pydantic 2.0.3 which is incompatible.
ERROR: jupyter-client 8.3.0 has requirement importlib-metadata>=4.8.3; python_version < "3.10", but you'll have importlib-metadata 1.5.0 which is incompatible.
ERROR: langsmith 0.0.5 has requirement pydantic<2,>=1, but you'll have pydantic 2.0.3 which is incompatible.
ERROR: langchain 0.0.234 has requirement pydantic<2,>=1, but you'll have pydantic 2.0.3 which is incompatible.
ERROR: langchain 0.0.234 has requirement SQLAlchemy<3,>=1.4, but you'll have sqlalchemy 1.3.12 which is incompatible.
ERROR: llama-index 0.7.9 has requirement sqlalchemy>=2.0.15, but you'll have sqlalchemy 1.3.12 which is incompatible.
ERROR: openai-whisper 20230314 has requirement tiktoken==0.3.1, but you'll have tiktoken 0.4.0 which is incompatible.
ERROR: replicate 0.8.4 has requirement pydantic<2,>1, but you'll have pydantic 2.0.3 which is incompatible.

**Comment by jackdong888** [comment]
run pip install -r requirements.txt and see above!

**Comment by pycui** [comment]
Have you tried update Python version?
