### ISSUE TITLE
APIconnection Error Error communicating with OpenAI

### ISSUE THREAD

**Issue by yinjie1949** [Shaunwei/RealChar#112]
Hi buddy 
My server and client have already up. My API-key is correct. Otherwise the server won't start.
I received a error Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 16.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
I used proxy clash because I am in china, I have the access for chatgpt, Please help me how to resolve this issue

**Comment by johndpope** [comment]
seems like you need to raise a ticket with the library that is used openai-whisper ?
https://github.com/openai/whisper

**Comment by pycui** [comment]
If seems related to the network situation with proxy/IP block thing. Would suggest to test if you can directly connect to whisper API, e.g. like this
```
curl https://api.openai.com/v1/audio/transcriptions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: multipart/form-data" \
  -F model="whisper-1" \
  -F file="@/path/to/file/openai.mp3"
```

**Comment by pycui** [comment]
Closing for now, feel free to reopen.

**Comment by Kevin-free** [comment]
> If seems related to the network situation with proxy/IP block thing. Would suggest to test if you can directly connect to whisper API, e.g. like this
> 
> ```
> curl https://api.openai.com/v1/audio/transcriptions \
>   -H "Authorization: Bearer $OPENAI_API_KEY" \
>   -H "Content-Type: multipart/form-data" \
>   -F model="whisper-1" \
>   -F file="@/path/to/file/openai.mp3"
> ```
> 
> If this doesn't work, it means you network has issue and can't connect to OpenAI

I also encountered the same problem, executing this command returned: curl: (26) Failed to open/read local data from file/application.

Does "@/path/to/file/openai.mp3" need to be modified? Or how to do it? Thanks!
