### ISSUE TITLE
Drop Down List Not Displaying List Items

### ISSUE THREAD

**Issue by Viddesh1** [Shaunwei/RealChar#124]
Thank you for creating such a amazing open source project. 😄 

I faced a drop down list element issue after selecting the drop down element at home page. Not Sure if it is working for all though. Below are the details 👇 :-

1) I hit https://realchar.ai/ in my web browser google chrome. 

2) When I tried to "Select as audio input device:" from the drop down list. But, I am unable to see the 3 list items present in that drop down list at once. Also only when I hover over with the mouse the elements present in the list are displayed in drop down list.

3) Rather, All the 3 list items including the default should be displayed to the end user.

![Drop_down_element_issue](https://github.com/Shaunwei/RealChar/assets/69793689/843713f0-be77-4794-b959-553892435b1a)

**Comment by pycui** [comment]
Cannot reproduce this issue. Can you try it out on the latest realchar.ai?

**Comment by Viddesh1** [comment]
It is working fine in the latest realchar.ai. Thanks!
