### ISSUE TITLE
can't have a voice conversation

### ISSUE THREAD

**Issue by SlookUP** [Shaunwei/RealChar#128]
I can't have a voice conversation on the official website, and I can't have a conversation on Windows, please ask me what I should do?

**Comment by SlookUP** [comment]
text is okay

**Comment by pycui** [comment]
Can you make sure you use a headphone?

**Comment by mysticaltech** [comment]
Try with chrome! Probably related to #154.

**Comment by danielxvcg** [comment]
I have met the same issue in Chrome and tried to debug the javascript "script.js" in my local environment. It seems that speechRecognition() raised the exception network error.

**Comment by LucianoSP** [comment]
I tried the demo on https://realchar.ai/ on Win11 and the audio doesn´t work on edge or chrome. Can´t have a voice conversation. Tried also on Chrome in Android and the same problem. Mic doesn´t work.

**Comment by pycui** [comment]
Closing this and consolidate Edge discussion to #154
