### ISSUE TITLE
docker: pull access denied for realtime-ai-character

### ISSUE THREAD

**Issue by eastcukt** [Shaunwei/RealChar#131]
I follow the guidance to install it by docker, an error occur when I run 'python3 cli.py docker-run' 

Error info:
Running Docker image: realtime-ai-character...
Unable to find image 'realtime-ai-character:latest' locally
docker: Error response from daemon: pull access denied for realtime-ai-character, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by eastcukt** [comment]
I tried docker login but it did not work, Has anyone had a similar problem?

**Comment by leo8198** [comment]
@eastcukt I had the same problem. Just change this code to point to the correct docker image docker and it will work.

`if db_file:
        subprocess.run(["docker", "run", "--env-file", ".env", "--name", name, "-p", "8000:8000",
                        "-v", f"{os.path.abspath(db_file)}:/realtime_ai_character/test.db", name)
    else:
        subprocess.run(["docker", "run", "--env-file", ".env",
                       "--name", name, "-p", "8000:8000", name])`

to: 

`if db_file:
        subprocess.run(["docker", "run", "--env-file", ".env", "--name", name, "-p", "8000:8000",
                        "-v", f"{os.path.abspath(db_file)}:/realtime_ai_character/test.db", "shaunly/real_char"])
    else:
        subprocess.run(["docker", "run", "--env-file", ".env",
                       "--name", name, "-p", "8000:8000", "shaunly/real_char"])`
