### ISSUE TITLE
Hello, I used the docker you provided and filled in the openai and ElevenLabs API tokens, but got this error. The page can open but there is no data. Thank you.

### ISSUE THREAD

**Issue by kkiqq22** [Shaunwei/RealChar#163]
Hello, I used the docker you provided and filled in the openai and ElevenLabs API tokens, but got this error. The page can open but there is no data. Thank you.
https://hub.docker.com/r/shaunly/real_char/tags

error：- handle_receive - websocket_routes.py - INFO - User #163130 closed the connection
Client #140436737317648 left the chat

**Comment by pycui** [comment]
Can you post the full error log? This doesn't show enough info

**Comment by kkiqq22** [comment]
![1690073673743](https://github.com/Shaunwei/RealChar/assets/20888251/d45a3f12-76ad-4b41-b55d-0e883e993186)
![1690073673775](https://github.com/Shaunwei/RealChar/assets/20888251/5996ae1a-9194-4e5d-acee-333692abfe37)
![1690073673789](https://github.com/Shaunwei/RealChar/assets/20888251/98c3fb64-56a6-47d8-9a94-38efc28d6ac0)
![1690073673806](https://github.com/Shaunwei/RealChar/assets/20888251/ad2b5843-63a6-4e61-b8e3-5bcf8e83798c)
My PC have headphone and microphone. thanks so much

**Comment by kkiqq22** [comment]
Moreover, I noticed that it's not just the microphone that cannot be read, the character data is also empty after clicking in.

**Comment by kkiqq22** [comment]
close
