### ISSUE TITLE
EKS deployment issue

### ISSUE THREAD

**Issue by jfaraklit** [Shaunwei/RealChar#168]
Had below issue with my docker build and tried shaunly/real_char:latest image  as well. Still below issue.
For some reason, characters don't show up. **WebSocket connection to 'wss://mydomainnamehidden/ws/63599' failed**

<img width="897" alt="image" src="https://github.com/Shaunwei/RealChar/assets/14077606/3f8b8254-879e-489e-88cc-a2882100c7e2">

in container  logs shows 404 not found
<img width="501" alt="image" src="https://github.com/Shaunwei/RealChar/assets/14077606/4938d8dd-3e25-4b57-86d1-22d3b6763cc4">

**Comment by jfaraklit** [comment]
Looks like it was my docker. I tried to use shaunly/real_char:latest and the  deploy was fine. But when for some reason character don't show up.

<img width="897" alt="image" src="https://github.com/Shaunwei/RealChar/assets/14077606/3f8b8254-879e-489e-88cc-a2882100c7e2">

**Comment by pycui** [comment]
Cool! Feel free to send PR to add/edit the sample yaml if would like.
