### ISSUE TITLE
The character still admit he is an AI

### ISSUE THREAD

**Issue by sofianhw** [Shaunwei/RealChar#169]
<img width="734" alt="image" src="https://github.com/Shaunwei/RealChar/assets/1507989/942baef8-3838-45c4-b9f5-0e8b2de218ab">

If we are asking more about feeling or something, AI still admit he/she was an AI, how to handle it?

**Comment by johndpope** [comment]
it's called "alignment" - you want to use an uncensored llm.
https://huggingface.co/TheBloke/Luna-AI-Llama2-Uncensored-GGML

**Comment by chenkang404** [comment]
is that running on windows, ios, or linux ? 
my code failed to run  in win.

**Comment by Shaunwei** [comment]
@sofianhw
I cannot reproduce. what did you prompt it before?

<img width="753" alt="image" src="https://github.com/Shaunwei/RealChar/assets/5101573/eca53670-fa95-41af-b276-612e1abc2055">

**Comment by sofianhw** [comment]
I ask : How about your feeling?
after that I ask : do you want to be my boyfriend

Now I cant handle it with scoping the topik that AI can talk
