### ISSUE TITLE
need to specify the default docker image tag as described in the README

### ISSUE THREAD

**Issue by xingdu-sce** [Shaunwei/RealChar#187]
I would assume the Default image tag referred in these places

https://github.com/Shaunwei/RealChar/blob/f3944cd4056f404aad3cbdcc3bae22a47a2d7cdb/cli.py#L14
https://github.com/Shaunwei/RealChar/blob/f3944cd4056f404aad3cbdcc3bae22a47a2d7cdb/cli.py#L28
https://github.com/Shaunwei/RealChar/blob/f3944cd4056f404aad3cbdcc3bae22a47a2d7cdb/cli.py#L47

all point to the image tag mentioned in the README
https://github.com/Shaunwei/RealChar/blob/f3944cd4056f404aad3cbdcc3bae22a47a2d7cdb/README.md?plain=1#L223

So either add an extra step to retag the image in the README, otherwise people will get confused.

**Comment by pycui** [comment]
Good point, I will add it

**Comment by pycui** [comment]
Done in https://github.com/Shaunwei/RealChar/pull/189. Thanks!
