### ISSUE TITLE
Without headphone, no sound play

### ISSUE THREAD

**Issue by zhoudaquan** [Shaunwei/RealChar#284]
Hi, I have managed to set up the repo in my remote server and connect via web browser successfully. However, after connecting, there are no sounds come out.. anyone has any suggestions? thanks a lot!

**Comment by pycui** [comment]
you would need to set up SSL to connect on remote server.

**Comment by zhoudaquan** [comment]
Hi, thanks for the reply.

I have already setup the SSH and all other functions are working as expected. Only the sound is not there.

Am I missing any configurations for the SSH setup that is specific for the sound?

**Comment by pycui** [comment]
Does it work locally for you?

SSH is not SSL. Suggest to check how to setup SSL locally (e.g. self-signed certificate)

**Comment by zhoudaquan** [comment]
> Does it work locally for you?
> 
> SSH is not SSL. Suggest to check how to setup SSL locally (e.g. self-signed certificate)

Hi,

Thanks for the reply. The problem has been solved. The issue is that the server port is not set properly and so the audio data is not sent out.
