### ISSUE TITLE
Where to find the button/checkbox for "Enable Google Search"?

### ISSUE THREAD

**Issue by zhoudaquan** [Shaunwei/RealChar#291]
I have cloned the main branch and run the repo. The UI seems to be much more simpler than the provided demo page and I cannot find the button for enabling the Google Search.

Can anyone help with this?

Thanks a lot.

**Comment by pycui** [comment]
You are likely using the legacy static webpage (localhost:8000). Please refer to the npm version in README.

**Comment by pycui** [comment]
Updated README to make this more clear

**Comment by zhoudaquan** [comment]
> Updated README to make this clear

Hi,

I have followed your suggestion with npm run in the remote server. However, when connect to the running cline, I got UI as follows:
![image](https://github.com/Shaunwei/RealChar/assets/13412208/9c0b70d9-87d5-444f-a27c-157dd5fb7302)


No button can be clicked...

Can you pelase advice what should I do next? Thanks!
