### ISSUE TITLE
Character Photo is not displayed correctly

### ISSUE THREAD

**Issue by zhoudaquan** [Shaunwei/RealChar#302]
Hi,

I have followed the tutorial and created a character in the same format as other characters in the community. However, the photo is not displayed. Are there any formats or configurations I need to do?

Thanks for the help.

![image](https://github.com/Shaunwei/RealChar/assets/13412208/c1684b9f-bd05-4747-a45e-fcc39a8a48ca)

**Comment by pycui** [comment]
You can check realtime_ai_character/restful_routes.py L83 to a local path
