### ISSUE TITLE
Error uploading image

### ISSUE THREAD

**Issue by blacksmithop** [Shaunwei/RealChar#328]
When uploading an image for a custom character the character gets created but the image appears to be blank.
This is confusing as the image preview is shown when the user uploads it.
Perhaps a more intuitive error message would be a better fit here since users might believe there was an error and go through character creation again (much like I did) before the notice it.
![image](https://github.com/Shaunwei/RealChar/assets/60320192/f327f219-d2f6-481e-b753-ef729211b165)

**Comment by pycui** [comment]
Yes we are aware of this issue and working on a fix

**Comment by pycui** [comment]
It's fixed on main and also will be released to the hosted version soon.

**Comment by blacksmithop** [comment]
Great news!
