### ISSUE TITLE
 How to have a continuous conversation without interruption?

### ISSUE THREAD

**Issue by guowc** [Shaunwei/RealChar#398]
I saw that the dialogue process in your demo video is continuous, but after I run the project locally, I need to manually turn on/off the recording button to end the recording. I hope to continuously monitor the input voice and interrupt the robot output like in your video demo, what should i do

**Comment by pycui** [comment]
Please use a headphone, or enable the "Open speaker" mode in advanced options.

**Comment by guowc** [comment]
I tried what you said but it doesn't seem to work? I still need to manually click the stop recording button to complete the speech-to-text operation. Like your demo video, the speech-to-text conversion cannot be automatically triggered when there is a long pause in speaking. Please tell me how to do it?

**Comment by guowc** [comment]
It seems to work fine in speech mode, but not consistently triggered by recording in conversation mode

**Comment by pycui** [comment]
oh in text mode, it's a push-to-talk mode, so it's expected you need to stop when you are done talking. If you want to do free speech please use the call mode.
