### ISSUE TITLE
Non-English voice playback is slow

### ISSUE THREAD

**Issue by ke-dev** [Shaunwei/RealChar#438]
Hi, my experience is that non-English languages don’t seem to be streaming. It has to wait until all messages are received before starting to play the voice, and sometimes it takes a long time to play the voice. Is this a problem with 11labs? Do you have anything to speed up the voice playback? method?

**Comment by Shaunwei** [comment]
what language are u using? the current audio segment is based on end of sentence like "." "!". does your language of choice has similar character?
