### ISSUE TITLE
google tts didn,t work

### ISSUE THREAD

**Issue by ke-dev** [Shaunwei/RealChar#443]
Hi, I deploy the project via render fellowing the tutorial, the google tts didn't work but the 11labs works fine and no error logs was found, how to make google tts work properly?

**Comment by Shaunwei** [comment]
does google tts work locally? u need to get google credential json from GCP

**Comment by ke-dev** [comment]
> does google tts work locally? u need to get google credential json from GCP

I get the json file, but it still didn't work properly. I gave up, but I have another question, how to change the voice id of EDGE_TTS. EDGE_TTS seems to be free and open source, but it didn't work when I changed its voice id. There was only one A male voice.

![0bd7cf2cb6403acdb880825d199efed](https://github.com/Shaunwei/RealChar/assets/59656387/24ae67b0-262e-43da-92b5-b65a5ce3f5cf)
