### ISSUE TITLE
Checkout this out if you are looking for an alternative😘

### ISSUE THREAD

**Issue by proxfly** [Shaunwei/RealChar#473]
Hello everyone! 😇

Introducing our project, [Talk](https://github.com/proxoar/talk)—an app that shares similarities with RealChar. With [Talk](https://github.com/proxoar/talk), you can engage in voice-based conversations with ChatGPT. The app is built with a refreshing user interface and allows you to customize the parameters of ChatGPT, Elevenlabs, and Google Text-to-Speech.

We hold deep respect for RealChar, as it served as a significant source of inspiration for us. Just for those seeking a different experience, we invite you to give [Talk](https://github.com/proxoar/talk) a try: [DEMO](https://talk.proxoar.com/)

If you're interested in deploying your own instance, you can access all the necessary resources at: https://github.com/proxoar/talk. Setting up your server using Docker is a pretty easy.

<img width="917" alt="Talk" src="https://github.com/Shaunwei/RealChar/assets/27894831/97c4f00e-2fb2-457b-ad83-4413bfde0a31">

![1](https://github.com/Shaunwei/RealChar/assets/27894831/50d02d68-16e0-4e5c-b202-a955640c0a88)

![2](https://github.com/Shaunwei/RealChar/assets/27894831/e73fb945-48fc-4f2e-a11f-451bce09e19f)

![3](https://github.com/Shaunwei/RealChar/assets/27894831/4be433f5-cfae-4bb8-9675-b169093c35d4)

**Comment by Shaunwei** [comment]
Thank you for providing an alternative.
