### ISSUE TITLE
can't run due to chroma  issue

### ISSUE THREAD

**Issue by DinoLiww** [Shaunwei/RealChar#75]
File "D:\Anaconda3\lib\site-packages\langchain\vectorstores\chroma.py", line 184, in add_texts
    self._collection.upsert(
AttributeError: 'Collection' object has no attribute 'upsert'
PersistentDuckDB del, about to run persist
Persisting DB to disk, putting it in the save folder ./chroma.db

**Comment by Shaunwei** [comment]
which version of chroma?

**Comment by Shaunwei** [comment]
I think in the discord channel. Upgrade your chroma will fix the issue.

**Comment by pycui** [comment]
This is an old issue that can be fixed by upgrading langchain. Closing
