### ISSUE TITLE
chromadb problems

### ISSUE THREAD

**Issue by sacredgrove23** [Shaunwei/RealChar#93]
---

**Issue Description:**

I'm encountering an issue with the `realtime_ai_character` project related to a deprecated configuration of Chroma. When I try to run the project using `python cli.py run-uvicorn`, I receive the following error message:

Replit

ValueError: You are using a deprecated configuration of Chroma. Please pip install chroma-migrate and run `chroma-migrate` to upgrade your configuration. See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Steps to Reproduce:**

1. Clone the repository and set up the environment as mentioned in the README.
2. Run the command `python cli.py run-uvicorn` to start the server.

**Expected Behavior:**

The project should start without any errors and the server should be accessible.

**Actual Behavior:**

The error message mentioned above is displayed, indicating a deprecated configuration of Chroma.

**Additional Information:**

- Python version: [3.9.2]
- Chroma version: [0.4.0]
- Other relevant details: [Linux on chromebook]

**Possible Solutions:**

I have tried running `chroma-migrate` as suggested in the error message, but it did not resolve the issue. I have also checked the Chroma configuration in my project files and environment variables, but everything seems to be in order. I'm unsure how to proceed further.

Any assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by pycui** [comment]
This is an chromadb issue - the error log prompt you migrate is also from chroma. The `chroma-migrate` tool should be able to help. Can you post this to  Chroma DB's discord https://discord.gg/8g5FESbj (as they suggested in their error message)?

**Comment by Imccccc** [comment]
I believe chromadb db provide a [break change](https://docs.trychroma.com/migration).
Try to set the `chromadb==0.3.29` to avoid this problem.
I believe the dependencies in `requirement.txt` should be versioned, python libraries get much fast development.

**Comment by jappre** [comment]
> 

works for me , thanks a lot!

**Comment by jappre** [comment]
> I believe chromadb db provide a [break change](https://docs.trychroma.com/migration). Try to set the `chromadb==0.3.29` to avoid this problem. I believe the dependencies in `requirement.txt` should be versioned, python libraries get much fast development.

works for me , thanks a lot!

**Comment by pycui** [comment]
Thanks, yes we found out the same. I will push for a change to fix tis for now.

**Comment by pycui** [comment]
Done https://github.com/Shaunwei/RealChar/pull/96

**Comment by Imccccc** [comment]
this issue should not be closed, I can patch a fix that compatible with chromadb 0.4.0

**Comment by pycui** [comment]
Sounds good,

**Comment by sacredgrove23** [comment]
uninstalling chromadb and installing the chromadb==0.3.29 worked for me. the program now runs. thanks.
