### ISSUE TITLE
Got `enumerateDevices` error when run a remote server and request from client

### ISSUE THREAD

**Issue by zhouqiang-cl** [Shaunwei/RealChar#98]
When I start a remote server and request from local, the web console reports
```
Uncaught TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at script.js:118:26
```

**Comment by pycui** [comment]
If running locally, this is expected (as microphone over web needs SSL). You can use the CLI to connect, it supports both audio/text interactions, so fully functionality (please use headphone). 

We will look into make the local run with web better. Stay tuned.

**Comment by zhouqiang-cl** [comment]
> 

got it, thank you for your reply. 
that means if I use SSL, it will work?

**Comment by zhouqiang-cl** [comment]
> If running locally, this is expected (as microphone over web needs SSL). You can use the CLI to connect, it supports both audio/text interactions, so fully functional (please use headphone).
> 
> We will look into make the local run with web better. Stay tuned.

got it, thank you for your reply.
that means if I use SSL, it will work?

**Comment by pycui** [comment]
Yes, I haven't tested it myself, but it should be able to do with Self-Signed Certificate

**Comment by zhouqiang-cl** [comment]
> Yes, I haven't tested it myself, but it should be able to do with Self-Signed Certificate

Yes. it works for https. 

but still have other error, but I don't know if it is just on my laptop or other config's

could you help to take a look? thank you very much

```
Playback failed because: NotSupportedError: Failed to load because no supported source was found.
```

**Comment by zhouqiang-cl** [comment]
> > Yes, I haven't tested it myself, but it should be able to do with Self-Signed Certificate
> 
> Yes. it works for https.
> 
> but still have other error, but I don't know if it is just on my laptop or other config's
> 
> could you help to take a look? thank you very much
> 
> ```
> Playback failed because: NotSupportedError: Failed to load because no supported source was found.
> ```

maybe need ELEVEN_LABS_API_KEY, I will take a look, thank you very much

**Comment by pycui** [comment]
@zhouqiang-cl can you check if you have a valid ElevenLabs API key and the account is in good state with billing?

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl can you check if you have a valid ElevenLabs API key and the account is in good state with billing?

got it, thank you, I will take a look

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl can you check if you have a valid ElevenLabs API key and the account is in good state with billing?

It works!!!
thank you so much

**Comment by polym** [comment]
It seems that using https on web browser is required.

**Comment by Kevin-free** [comment]
> @zhouqiang-cl can you check if you have a valid ElevenLabs API key and the account is in good state with billing?

I also report this error, and there are still a lot of Characters used in the llElevenLabs account, and I change the API Key of the account, and the error is still reported:
```
Playback failed because: NotSupportedError: Failed to load because no supported source was found.
```
What should I do?

**Comment by pycui** [comment]
Maybe double check your billing and account status. You can test if your elevenlabs key works or not by testing in https://api.elevenlabs.io/docs#/text-to-speech/Text_to_speech_v1_text_to_speech__voice_id__post
